name: Image buid

on:
  schedule:
      - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      image-require-update: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Docker Image Update Checker
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: pihole/pihole:latest
          image: devzwf/mytest:latest
        if: ${{ github.event_name == 'schedule' }}
        env:
          DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}

  build:
    needs: check
    if: ${{ github.event_name != 'schedule' || needs.check.outputs.image-require-update == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch latest release tag for pihole
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        id: latest-tag-pihole
        with:
          repository: pi-hole/docker-pi-hole

      - name: Fetch latest release tag 
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        id: latest-tag
        with:
          repository: devzwf/mytest

      - name: Extract version number
        id: extract_version
        run: echo "version=$(echo ${{ steps.latest-tag.outputs.release }} | awk -F'-z' '{print $2}')" >> $GITHUB_OUTPUT 

      - name: Increment version number
        id: increment_version
        run: echo "version=$(printf \"%03d\" $((10#${{ steps.extract_version.outputs.version }} + 1)))" >> $GITHUB_OUTPUT


      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64
          push: true
          provenance: false
          tags: |
            devzwf/mytest:latest
            devzwf/mytest:${{ steps.latest-tag-pihole.outputs.release }}-z${{ steps.increment_version.outputs.version }}
